// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'npx tsx ./prisma/seed.ts',
  },
  datasource: {
    url: "mysql://root:Dragon851171!@localhost:3306/computer_service_site_db",
    // url: process.env["DATABASE_URL"],
  },
});
