import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import SVGIcon from "@/components/SVGIcon/SVGIcon";
import SiteNavigation from "@/components/UI/SiteNavigation/SiteNavigation";
import SiteFooter from "@/components/Site/SiteFooter/SiteFooter";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App", // Site Title
  description: "Generated by create next app", // Site Description
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="ru"
    >

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
        {/* <header> */}
        <SiteNavigation />
        {/* <nav className="site-navigation">
            <ul className="site-navigation__left">
              <li className="site-navigation__button">
                <Image
                  width={144}
                  height={36}
                  src="/site-temp-logo.svg"
                  alt=""
                />
              </li>
            </ul>

            <ul className="site-navigation__middle --desktop-only">
              <li className="site-navigation__button link">
                <Link href="/">Главная</Link>
              </li>
              <li className="site-navigation__button link">
                <Link href="/services">Услуги</Link>
              </li>
              <li className="site-navigation__button link">
                <Link href="/about">О нас</Link>
              </li>
              <li className="site-navigation__button link">
                <Link href="/contacts">Контакты</Link>
              </li>
            </ul>

            <ul className="site-navigation__right --desktop-only">
              <li className="site-navigation__button">
                <div className="site-navigation__contacts-block">
                  <span>
                    <SVGIcon
                      width={20}
                      height={20}
                      style={{ marginRight: '8px' }}
                      imgSrc="/icons/turbowarp/phone.svg"
                    />
                    +375(29)123-45-67
                  </span>
                  <span>
                    <SVGIcon
                      width={20}
                      height={20}
                      style={{ marginRight: '8px' }}
                      imgSrc="/icons/turbowarp/time-clock.svg"
                    />
                    пн-пт 10:00 - 19:00
                  </span>
                </div>
              </li>
            </ul>
            <ul className="site-navigation__right --mobile-only">
              <li className="site-navigation__button">
                <button className={`mobile-menu-button ${isMobileMenuOpened ? 'active' : ''}`}></button>
              </li>
            </ul>
          </nav> */}
        {/* </header> */}

        <main>{children}</main>

        <SiteFooter />

      </body>
    </html >
  );
}
